### ISSUE TITLE
ERROR: failed to bootstrap from leader

### ISSUE THREAD

**Issue by varmaraju** [kostiantyn-nemchenko/ansible-role-patroni#37]
After executed the this role ETCD cluster health is good and 

etcdctl cluster-health
member 66070623373786c7 is healthy: got healthy result from http://192.168.33.10:2379
member a5bc874f58c33150 is healthy: got healthy result from http://192.168.33.13:2379
member beea9366978d9511 is healthy: got healthy result from http://192.168.33.14:2379
cluster is healthy

and we facing the issue at patroni like ERROR: failed to bootstrap . even Patroni status is fine  can you please help us to fix this issue. 

sudo systemctl status patroni
● patroni.service - Runners to orchestrate a high-availability PostgreSQL
   Loaded: loaded (/etc/systemd/system/patroni.service; enabled; vendor preset: enabled)
   Active: active (running) since Thu 2018-11-15 15:45:52 UTC; 18h ago
 Main PID: 20451 (patroni)
    Tasks: 4
   Memory: 24.7M
      CPU: 2min 47.226s
   CGroup: /system.slice/patroni.service
           └─20451 /usr/bin/python /usr/local/bin/patroni /etc/patroni/192.168.33.10.yml

Nov 16 09:47:49 server10 patroni[20451]: 2018-11-16 09:47:49,753 INFO: trying to bootstrap from leader '192.168.33.13'
Nov 16 09:47:49 server10 patroni[20451]: pg_basebackup: could not connect to server: FATAL:  no pg_hba.conf entry for replication connection from host "192.168.33.10", user "replicator", SSL off
Nov 16 09:47:49 server10 patroni[20451]: pg_basebackup: removing data directory "/var/lib/postgresql/10/main"
Nov 16 09:47:49 server10 patroni[20451]: 2018-11-16 09:47:49,764 ERROR: Error when fetching backup: pg_basebackup exited with code=1
Nov 16 09:47:49 server10 patroni[20451]: 2018-11-16 09:47:49,764 WARNING: Trying again in 5 seconds
Nov 16 09:47:54 server10 patroni[20451]: pg_basebackup: could not connect to server: FATAL:  no pg_hba.conf entry for replication connection from host "192.168.33.10", user "replicator", SSL off
Nov 16 09:47:54 server10 patroni[20451]: pg_basebackup: removing data directory "/var/lib/postgresql/10/main"
Nov 16 09:47:54 server10 patroni[20451]: 2018-11-16 09:47:54,780 ERROR: Error when fetching backup: pg_basebackup exited with code=1
Nov 16 09:47:54 server10 patroni[20451]: 2018-11-16 09:47:54,780 ERROR: failed to bootstrap from leader '192.168.33.13'
Nov 16 09:47:54 server10 patroni[20451]: 2018-11-16 09:47:54,780 INFO: Removing data directory: /var/lib/postgresql/10/main

**Comment by kostiantyn-nemchenko** [comment]
Hi, @varmaraju !

First, I would not rely on the `systemctl` output to check the cluster health. Patroni has the great `patronictl` command to manage a cluster and get its state. I recommend learning more about it.

> Nov 16 09:47:49 server10 patroni[20451]: pg_basebackup: could not connect to server: FATAL: no pg_hba.conf entry for replication connection from host "192.168.33.10", user "replicator", SSL off

This error message is quite straightforward. You should put the correct rules into pg_hba.conf file to allow replication connections from the remote nodes. 
[patroni_postgresql_pg_hba](https://github.com/kostiantyn-nemchenko/ansible-role-patroni/blob/master/defaults/main.yml#L115) variable is responsible for that, which is empty by default.

**Comment by varmaraju** [comment]
Thank you for response
I have updated the configuration "pg_hba" manually in the configuration. Via Play book "pg_hba" lines are not added into the patroni.yml file. For testing purpose I have added manually and restarted the patroni. Even after added pg_hba I am facing same issues.  

scope: main
namespace: /service/
name: 192.168.33.10

restapi:
  listen: 0.0.0.0:8008
  connect_address: 192.168.33.10:8008

etcd:
  hosts: 127.0.0.1:2379
  protocol: http

bootstrap:
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    maximum_lag_on_failover: 1048576
    master_start_timeout: 300
    synchronous_mode: false
    postgresql:
      use_pg_rewind: true
      use_slots: true
      parameters:
        max_connections: 100
        max_locks_per_transaction: 64
        max_worker_processes: 8
        max_prepared_transactions: 0
        wal_level: replica
        wal_log_hints: on
        track_commit_timestamp: off
        max_wal_senders: 10
        max_replication_slots: 10
        wal_keep_segments: 0
  initdb:
    - encoding: UTF8
    - data-checksums
  pg_hba:
    - host replication replicator 127.0.0.1/32 md5
    - host replication replicator 192.168.33.10/0 md5
    - host replication replicator 192.168.33.13/0 md5
    - host replication replicator 192.168.33.14/0 md5
    - host all all 0.0.0.0/0 md5
  users:
    postgres:
      password: supersecretpostgrespasswd
    replicator:
      password: repuserpasswd
      options:
        - replication

postgresql:
  use_unix_socket: true
  listen: 0.0.0.0:5432
  connect_address: 192.168.33.10:5432
  data_dir: /var/lib/postgresql/10/main
  bin_dir: /usr/lib/postgresql/10/bin
  config_dir: /var/lib/postgresql/10/main
  pgpass: /var/lib/postgresql/.pgpass
  authentication:
    superuser:
      username: postgres
      password: supersecretpostgrespasswd
    replication:
      username: replicator
      password: repuserpasswd
  create_replica_method:
    - basebackup
  parameters:
    unix_socket_directories: /var/run/postgresql
  pg_ctl_timeout: 60
  use_pg_rewind: true
  pg_rewind:
    username: postgres
    password: supersecretpostgrespasswd
  remove_data_directory_on_rewind_failure: false

watchdog:
  mode: automatic
  device: /dev/watchdog
  safety_margin: 5

tags:
    nofailover: false
    noloadbalance: false
    clonefrom: false
    nosync: false

**Comment by varmaraju** [comment]
Thank you for your response sir. 
Now I have fixed the issue.

**Comment by patsevanton** [comment]
Hello!
Not fixed.

```
pg_basebackup: could not connect to server: FATAL:  no pg_hba.conf entry for replication connection from host "192.168.88.149", user "replicator", SSL off
```

```
bootstrap:
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    maximum_lag_on_failover: 1048576
    master_start_timeout: 300
    synchronous_mode: false
    postgresql:
      use_pg_rewind: true
      use_slots: true
      parameters:
        max_connections: 100
        max_locks_per_transaction: 64
        max_worker_processes: 8
        max_prepared_transactions: 0
        wal_level: replica
        wal_log_hints: on
        track_commit_timestamp: off
        max_wal_senders: 10
        max_replication_slots: 10
        wal_keep_segments: 0
  initdb:
    - encoding: UTF8
    - data-checksums
  users:
    postgres:
      password: supersecretpostgrespasswd
    replicator:
      password: repuserpasswd
      options:
        - replication
```

https://github.com/kostiantyn-nemchenko/ansible-role-patroni/blob/master/defaults/main.yml#L115
Need add to pg_hba:

```
host    replication     replicator      node1/32       trust
host    replication     replicator      node2/32       trust
host    replication     replicator      node3/32       trust
```

trust or may be md5

**Comment by kostiantyn-nemchenko** [comment]
I left that variable empty intentionally from a security perspective. IMO it's user's responsibility to set correct rules there depending on the environment and authentication policies. Will add some basic rules and comments in the documentation regarding configuring that config section.

**Comment by varmaraju** [comment]
https://github.com/kostiantyn-nemchenko/ansible-role-patroni/blob/master/defaults/main.yml#L115, If i want get all the hostnames/Ipaddress  like below I think we should  use for loop. 

host    replication     replicator      node1/32       trust
host    replication     replicator      node2/32       trust
host    replication     replicator      node3/32       trust


As of now I have defined like below

etcd_cluster_group: etcd_cluster
etcd_cluster_master: "{{ groups[etcd_cluster_group][0] }}"
etcd_cluster_master1: "{{ groups[etcd_cluster_group][1] }}"
etcd_cluster_master2: "{{ groups[etcd_cluster_group][2] }}"


patroni_postgresql_pg_hba:
 - { type: "host", database: "all",         user: "all",                                address: "0.0.0.0/0", method: "md5" }
 - { type: "host", database: "replication", user: "{{ patroni_replication_username }}", address: "0.0.0.0/0", method: "md5" }
 - { type: "host", database: "replication", user: "{{ patroni_replication_username }}", address: "{{ groups[etcd_cluster_group][0] }}/0", method: "md5" }
 - { type: "host", database: "replication", user: "{{ patroni_replication_username }}", address: "{{ groups[etcd_cluster_group][1] }}/0", method: "md5" }
 - { type: "host", database: "replication", user: "{{ patroni_replication_username }}", address: "{{ groups[etcd_cluster_group][2] }}/0", method: "md5" }


Since I have three I have given like that but if  I have more than that it should take from Inventory. May I know how to do that. Please let me know how to do that

**Comment by patsevanton** [comment]
@varmaraju good idea.
Please try https://github.com/patsevanton/ansible-role-patroni  -this is playbook with custom fix

Pull Request
https://github.com/kostiantyn-nemchenko/ansible-role-patroni/pull/38

**Comment by varmaraju** [comment]
Thank you sir for your response 
https://github.com/patsevanton/ansible-role-patroni
https://github.com/patsevanton/ansible-role-patroni/blob/master/defaults/main.yml/ here the following parameter is commented only 
patroni_postgresql_pg_hba  I have seen commented lines only

**Comment by patsevanton** [comment]
Yes. Because i dont use 
```
etcd_cluster_group: etcd_cluster
etcd_cluster_master: "{{ groups[etcd_cluster_group][0] }}"
etcd_cluster_master1: "{{ groups[etcd_cluster_group][1] }}"
etcd_cluster_master2: "{{ groups[etcd_cluster_group][2] }}"
```
https://github.com/patsevanton/ansible-role-patroni/blob/master/templates/patroni.yml.j2#L68
This pg_hba is work.

**Comment by varmaraju** [comment]
Thank you for your reply. we should not use 0.0.0.0/0. we have use all our hosts only sir.

**Comment by patsevanton** [comment]
@varmaraju i dont use 0.0.0.0/0 too.
But i dont know how correct write this code.

Are you variable ansible_default_ipv4"  return 127.0.0.0  ?
i think return real ip network adapter

My inventory:
[all]
node1 ansible_host=192.168.0.1
node2 ansible_host=192.168.0.2
node3 ansible_host=192.168.0.3

[patroni]
node1
node2
node3

Try

**Comment by patsevanton** [comment]
@kostiantyn-nemchenko Please review pull request. I can refactored pull request for accept.
If code not accept i can remove and change.

**Comment by patsevanton** [comment]
@varmaraju i think kostiantyn-nemchenko busy.
Need questionon stackoverflow. Are you can?

**Comment by varmaraju** [comment]
@patsevanton Thank you for reply, Yes we will post this in stack-over flow also, please your side you can post. from my side I will post, if any get reply we will communicate in this channel   I think we can get more than one node  in templates using for loop , but in variable declaration only how can we get loop

**Comment by patsevanton** [comment]
My proposal try:
```
postgresql:
  parameters:
    hba_file: /path/to/custom/pg_hba.conf
    config_file: /path/to/custom/postgresql.conf
```
https://github.com/zalando/patroni/issues/53#issuecomment-143144668

**Comment by kostiantyn-nemchenko** [comment]
@varmaraju @patsevanton 

As default value I would suggest something like this:
```
patroni_bootstrap_pg_hba: "
  {%- set pg_hba = [dict(type='host', database='all', user='all', address='0.0.0.0/0', method='md5')] %}
  {%- for host in play_hosts %}
  {{- pg_hba.append(dict(type='host', database='replication', user=patroni_replication_username, address=hostvars[host]['ansible_host'] + '/32', method='md5')) }}
  {%- endfor %}
  {{- pg_hba -}}"
```

But this solution has two main disadvantages:
1) `'0.0.0.0/0'` is too dangerous and could be used only for testing purposes. You have to provide the correct rules depending on the requirements and environment.
2) `play_hosts` magic variable can contain other patroni nodes not from the current cluster. You have to set the inventory file properly or use for example `groups['patroni']`, where the `patroni` group contains only needed hosts.

**Comment by patsevanton** [comment]
@kostiantyn-nemchenko why dont user

```yaml
postgresql:
  parameters:
    hba_file: /path/to/custom/pg_hba.conf
```
?
Customers will be add line pg_hba.conf and patroni_bootstrap_pg_hba will not be use!

**Comment by varmaraju** [comment]
@kostiantyn-nemchenko  Thank you for your reply. I will try to test in that way

**Comment by varmaraju** [comment]
@kostiantyn-nemchenko, That is issue is fixed. Now I am facing below error.

2018-11-22T03:36:01-08:00 daemon:info [1e] patroni (1818): 2018-11-22 03:36:01,847 ERROR: Exception when changing replication slots
2018-11-22T03:36:01-08:00 daemon:info [1e] patroni (1818): Traceback (most recent call last):
2018-11-22T03:36:01-08:00 daemon:info [1e] patroni (1818):   File "/usr/local/lib/python2.7/dist-packages/patroni/postgresql.py", line 1571, in sync_replication_slots
2018-11-22T03:36:01-08:00 daemon:info [1e] patroni (1818):     self.load_replication_slots()
2018-11-22T03:36:01-08:00 daemon:info [1e] patroni (1818):   File "/usr/local/lib/python2.7/dist-packages/patroni/postgresql.py", line 1540, in load_replication_slots
2018-11-22T03:36:01-08:00 daemon:info [1e] patroni (1818):     cursor = self._query('SELECT slot_name, slot_type, plugin, database FROM pg_catalog.pg_replication_slots')
2018-11-22T03:36:01-08:00 daemon:info [1e] patroni (1818):   File "/usr/local/lib/python2.7/dist-packages/patroni/postgresql.py", line 491, in _query
2018-11-22T03:36:01-08:00 daemon:info [1e] patroni (1818):     raise PostgresConnectionException('connection problems')
2018-11-22T03:36:01-08:00 daemon:info [1e] patroni (1818): PostgresConnectionException: 'connection problems'
2018-11-22T03:36:01-08:00 daemon:info [1e] patroni (1818): 2018-11-22 03:36:01,854 INFO: Error communicating with PostgreSQL. Will try again later

**Comment by patsevanton** [comment]
hmm. i try later.

**Comment by varmaraju** [comment]
@kostiantyn-nemchenko, Now I am facing below error. But I did not face any issues on testing environment, when I have test in pre prod , Play book is running file but I am seeing below errors in logs. May I know why these errors are occurring. due to patroni ?

2018-11-22T03:36:01-08:00 daemon:info [1e] patroni (1818): 2018-11-22 03:36:01,847 ERROR: Exception when changing replication slots
2018-11-22T03:36:01-08:00 daemon:info [1e] patroni (1818): Traceback (most recent call last):
2018-11-22T03:36:01-08:00 daemon:info [1e] patroni (1818): File "/usr/local/lib/python2.7/dist-packages/patroni/postgresql.py", line 1571, in sync_replication_slots
2018-11-22T03:36:01-08:00 daemon:info [1e] patroni (1818): self.load_replication_slots()
2018-11-22T03:36:01-08:00 daemon:info [1e] patroni (1818): File "/usr/local/lib/python2.7/dist-packages/patroni/postgresql.py", line 1540, in load_replication_slots
2018-11-22T03:36:01-08:00 daemon:info [1e] patroni (1818): cursor = self._query('SELECT slot_name, slot_type, plugin, database FROM pg_catalog.pg_replication_slots')
2018-11-22T03:36:01-08:00 daemon:info [1e] patroni (1818): File "/usr/local/lib/python2.7/dist-packages/patroni/postgresql.py", line 491, in _query
2018-11-22T03:36:01-08:00 daemon:info [1e] patroni (1818): raise PostgresConnectionException('connection problems')
2018-11-22T03:36:01-08:00 daemon:info [1e] patroni (1818): PostgresConnectionException: 'connection problems'
2018-11-22T03:36:01-08:00 daemon:info [1e] patroni (1818): 2018-11-22 03:36:01,854 INFO: Error communicating with PostgreSQL. Will try again later

**Comment by varmaraju** [comment]
I have seen those logs /var/log/messages. When I have have checked the postgres.conf I did not find any log location. But I have checked /var/log/postgresql in this location to verify logs. I did not find any logs in this location. 
When I google I have found the following
https://github.com/zalando/patroni/issues/275

**Comment by kostiantyn-nemchenko** [comment]
Something is wrong with your postgres settings. You have to investigate the issue on your own.

**Comment by patsevanton** [comment]
I am sorry. busy on work. help/check/try later

**Comment by varmaraju** [comment]
@kostiantyn-nemchenko, @patsevanton  Thank you for you co-operation the problem is, even If I uncommented the default lines(patroni_postgresql_pg_hba), pg_hba.conf file expect 127.0.0.0 and local trust files. we can't edit manually we have to go with via playbook only. After that I made a file like below.   I got answer from below blog.
https://github.com/zalando/patroni/issues/109

https://github.com/kostiantyn-nemchenko/ansible-role-patroni/blob/master/defaults/main.yml#L115


patroni_postgresql_pg_hba variable
default one:  
patroni_bootstrap_pg_hba: []
#  - { type: "host", database: "all",         user: "all",                                address: "0.0.0.0/0", method: "md5" }
#  - { type: "host", database: "replication", user: "{{ patroni_replication_username }}", address: "0.0.0.0/0", method: "md5" }

***********************************

etcd_cluster_group: etcd_cluster
etcd_cluster_master: "{{ groups[etcd_cluster_group][0] }}"
etcd_cluster_master1: "{{ groups[etcd_cluster_group][1] }}"
etcd_cluster_master2: "{{ groups[etcd_cluster_group][2] }}"

patroni_postgresql_pg_hba:
 - { type: "local", database: "all",         user: "all",                                method: "trust"}
 - { type: "host", database: "all",         user: "all",                                address: "127.0.0.1/32", method: "trust"}
 - { type: "host", database: "replication", user: "{{ patroni_replication_username }}", address: "127.0.0.1/0", method: "md5" }
 - { type: "host", database: "replication", user: "{{ patroni_replication_username }}", address: "{{ groups[etcd_cluster_group][0] }}/0", method: "md5" }
 - { type: "host", database: "replication", user: "{{ patroni_replication_username }}", address: "{{ groups[etcd_cluster_group][1] }}/0", method: "md5" }
 - { type: "host", database: "replication", user: "{{ patroni_replication_username }}", address: "{{ groups[etcd_cluster_group][2] }}/0", method: "md5" }
 - { type: "host", database: "replication", user: "{{ patroni_replication_username }}", address: "0.0.0.0/0", method: "md5" }
 - { type: "host", database: "all",         user: "all",                                address: "0.0.0.0/0", method: "md5" }


@kostiantyn-nemchenko, if you don't mine if you update the Read.md document regarding "  patroni_postgresql_pg_hba". with your proper comments that would great healp for other people will 


Really Thank you for time and given  the reply for my queries.
